version: '1.0'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_started
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  
  postgres:
    image: postgres:18-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data: